[jupiter.mysql.test]
    dialect = "postgres"
    connMaxLifetime = "300s"
    debug = true
    dsn = "root:root@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local&readTimeout=1s&timeout=1s&writeTimeout=3s"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
    disableTrace = false
    disableMetric = false

[jupiter.postgres.dev]
    dialect = "postgres"
    connMaxLifetime = "300s"
    debug = true
    dsn = "user=cebtc password=cebtc DB.name=cebtc-admin host=localhost port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
    disableTrace = false
    disableMetric = false

[jupiter.trace.jaeger]
     enableRPCMetrics = false
     [jupiter.trace.jaeger.sampler]
          type = "const"
          param = 0.001